use_default_settings: true
search:
  formats:
    - html
    - json
server:
  secret_key: "@searxngSecret@"
  bind_address: 0.0.0.0
  port: @searxngPort@
# default の google / ddg 等はブロックされる
engines:
  - name: bing
    disabled: false
  - name: mojeek
    disabled: false
  - name: yandex
    disabled: false
  - name: presearch
    disabled: false
