model = "@codexModel@"
approval_policy = "never"
default_permissions = "dev"

[permissions.dev]
description = "workspace general profile"
extends = ":workspace"

[permissions.dev.filesystem]
":workspace_roots"."." = "write"
":workspace_roots".".git" = "write"
"@homeDir@/workspace" = "write"
"@homeDir@/projects" = "write"

[permissions.dev.network]
enabled = true

[tui.model_availability_nux]
"@codexModel@" = 4
