keys:
  recovery: age1vd93az02nf3hgjnjqg33esdaxdgsuzlrgx8x70wqs23ahyqwr4wq7klkzz
  hosts:
    nixos: age18q3dcahkp6xqqcfqc6gr9s8g8hctdpr64n2407umlmj84tmx534skmxujr
creation_rules:
  - path_regex: ^secrets\.yaml$
    key_groups:
      - age:
          - age1vd93az02nf3hgjnjqg33esdaxdgsuzlrgx8x70wqs23ahyqwr4wq7klkzz
          - age18q3dcahkp6xqqcfqc6gr9s8g8hctdpr64n2407umlmj84tmx534skmxujr
