{
  pkgs,
  lib,
  hostConfig,
  self,
  ...
}:

let
  homeConfig = hostConfig.home-manager.users.${hostConfig.dotfiles.host.username};
  lspServers = builtins.attrValues hostConfig.dotfiles.toolchain.lsp;
  expectedLspNames = [
    "bash"
    "csharp"
    "java"
    "nix"
    "python"
    "rust"
    "typescript"
  ];
  lspRosterIsValid =
    servers:
    servers != { } && lib.sort builtins.lessThan (builtins.attrNames servers) == expectedLspNames;
  normalLspEvaluation = builtins.tryEval (
    assert lspRosterIsValid hostConfig.dotfiles.toolchain.lsp;
    true
  );
  emptyLspEvaluation = builtins.tryEval (
    assert lspRosterIsValid { };
    true
  );
  toolchain = hostConfig.dotfiles.toolchain.packages;
in
{
  # 宣言した command が package に無いと、CLI 側は起動時まで気付かない
  lsp-command-present =
    assert normalLspEvaluation.success;
    assert !emptyLspEvaluation.success;
    assert lspServers != [ ];
    assert lib.all (server: lib.elem server.package homeConfig.home.packages) lspServers;
    assert lib.all (
      server: lib.all (extension: lib.hasPrefix "." extension) (builtins.attrNames server.extensions)
    ) lspServers;
    pkgs.runCommandLocal "check-lsp-command-present" { nativeBuildInputs = [ pkgs.coreutils ]; } (
      lib.concatMapStrings (server: ''
        test -x ${server.package}/bin/${server.command}
      '') lspServers
      + "touch $out"
    );

  # 上流 release の binary は同梱 library を欠くと build は通って実行時に落ちる
  toolchain-binary-runs =
    pkgs.runCommandLocal "check-toolchain-binary-runs" { nativeBuildInputs = [ pkgs.coreutils ]; }
      ''
        set -euo pipefail

        ${lib.getExe toolchain.actrun} --help > actrun-help
        grep -q . actrun-help
        touch $out
      '';

  git-commit-message-contract =
    pkgs.runCommandLocal "check-git-commit-message-contract"
      {
        nativeBuildInputs = with pkgs; [
          bash
          coreutils
          gnugrep
        ];
      }
      ''
        set -euo pipefail

        hook=${self}/toolchain/git/assets/hooks/commit-msg

        expect_accept() {
          local name="$1"
          shift
          printf '%s\n' "$@" > "$name"
          if ! bash "$hook" "$name" > "$name.stdout" 2> "$name.stderr"; then
            echo "commit-msg rejected valid fixture: $name" >&2
            cat "$name.stderr" >&2
            exit 1
          fi
        }

        expect_reject() {
          local name="$1"
          shift
          printf '%s\n' "$@" > "$name"
          if bash "$hook" "$name" > "$name.stdout" 2> "$name.stderr"; then
            echo "commit-msg accepted invalid fixture: $name" >&2
            exit 1
          fi
        }

        for type in feat fix refactor docs test build ci chore style perf revert; do
          expect_accept "valid-$type" "$type: 日本語の要約"
        done
        expect_accept comments "fix: 日本語の要約" "# Git が追加するコメント"
        expect_accept tailwind "docs: Created with Tailwind の例を直す"
        expect_accept non-attribution "fix: Generated by maintainer の表記を直す"
        expect_accept samurai "fix: Samurai により生成する処理を直す"

        japanese_limit="fix: "
        for _ in $(seq 1 45); do
          japanese_limit="''${japanese_limit}あ"
        done
        printf '%s\n' "$japanese_limit" > japanese-limit
        if ! LC_ALL=C bash "$hook" japanese-limit > japanese-limit.stdout 2> japanese-limit.stderr; then
          echo "commit-msg counted UTF-8 bytes instead of characters" >&2
          cat japanese-limit.stderr >&2
          exit 1
        fi

        expect_reject arbitrary "日本語の要約"
        expect_reject attribution "fix: この commit は Codex により生成"
        expect_reject attribution-period "fix: この commit は Codex により生成。"
        expect_reject attribution-passive "fix: この commit は OpenAI により作成された。"
        expect_reject attribution-exclamation "fix: この commit は AI によって執筆！"
        expect_reject attribution-polite "fix: この commit は Codex により生成済みです"
        expect_reject attribution-no-space "fix: この commit は Codexにより生成"
        expect_reject attribution-generic-no-space "fix: この commit は AIにより生成"
        expect_reject attribution-multiple-spaces "fix: Generated  by Codex の帰属"
        expect_reject attribution-tab $'fix: Generated\tby Codex の帰属'
        expect_reject openai-attribution "fix: この commit は OpenAI により生成"
        expect_reject scope "fix(agents): 日本語の要約"
        expect_reject tab $'fix:\t日本語の要約'
        expect_reject body "fix: 日本語の要約" "" "理由を本文に書く"
        expect_reject breaking "feat!: 日本語の要約"
        expect_reject english "fix: update README"
        expect_reject unknown-type "release: 日本語の要約"
        expect_reject over-limit "''${japanese_limit}あ"

        touch "$out"
      '';

}
