{
  pkgs,
  lib,
  hostConfig,
  self,
  ...
}:

let
  homeConfig = hostConfig.home-manager.users.${hostConfig.dotfiles.workstation.username};
  lspServers = builtins.attrValues hostConfig.dotfiles.toolchain.lsp;
  expectedLspNames = [
    "bash"
    "csharp"
    "java"
    "nix"
    "python"
    "rust"
    "typescript"
  ];
  lspRosterIsValid =
    servers:
    servers != { } && lib.sort builtins.lessThan (builtins.attrNames servers) == expectedLspNames;
  normalLspEvaluation = builtins.tryEval (
    assert lspRosterIsValid hostConfig.dotfiles.toolchain.lsp;
    true
  );
  emptyLspEvaluation = builtins.tryEval (
    assert lspRosterIsValid { };
    true
  );
  toolchain = hostConfig.dotfiles.toolchain.packages;
in
{
  # 宣言した command が package に無いと、CLI 側は起動時まで気付かない
  lsp-command-present =
    assert normalLspEvaluation.success;
    assert !emptyLspEvaluation.success;
    assert lspServers != [ ];
    assert lib.all (server: lib.elem server.package homeConfig.home.packages) lspServers;
    assert lib.all (
      server: lib.all (extension: lib.hasPrefix "." extension) (builtins.attrNames server.extensions)
    ) lspServers;
    pkgs.runCommandLocal "check-lsp-command-present" { nativeBuildInputs = [ pkgs.coreutils ]; } (
      lib.concatMapStrings (server: ''
        test -x ${server.package}/bin/${server.command}
      '') lspServers
      + "touch $out"
    );

  # 上流 release の binary は同梱 library を欠くと build は通って実行時に落ちる
  toolchain-binary-runs =
    pkgs.runCommandLocal "check-toolchain-binary-runs" { nativeBuildInputs = [ pkgs.coreutils ]; }
      ''
        set -euo pipefail

        ${lib.getExe toolchain.actrun} --help > actrun-help
        grep -q . actrun-help

        ${lib.getExe toolchain.zvec-grep} version > zg-version
        grep -Fxq '0.2.1' zg-version
        printf '%s\n' 'semantic search needle' > zg-fixture
        ${lib.getExe toolchain.zvec-grep} query --rg -n -F 'semantic search needle' zg-fixture > zg-exact
        grep -Fq 'semantic search needle' zg-exact
        touch $out
      '';

  git-commit-message-contract =
    pkgs.runCommandLocal "check-git-commit-message-contract"
      {
        nativeBuildInputs = with pkgs; [
          bash
          coreutils
          gnugrep
        ];
      }
      ''
        set -euo pipefail

        hook=${self}/toolchain/git/assets/hooks/commit-msg

        expect_accept() {
          local name="$1"
          shift
          printf '%s\n' "$@" > "$name"
          if ! bash "$hook" "$name" > "$name.stdout" 2> "$name.stderr"; then
            echo "commit-msg rejected valid fixture: $name" >&2
            cat "$name.stderr" >&2
            exit 1
          fi
        }

        expect_reject() {
          local name="$1"
          shift
          printf '%s\n' "$@" > "$name"
          if bash "$hook" "$name" > "$name.stdout" 2> "$name.stderr"; then
            echo "commit-msg accepted invalid fixture: $name" >&2
            exit 1
          fi
        }

        expect_attribution() {
          expect_reject "$@"
          if ! grep -q '^AI attribution: ' "$1.stderr"; then
            echo "commit-msg rejected $1 without reporting AI attribution" >&2
            cat "$1.stderr" >&2
            exit 1
          fi
        }

        accept_each() {
          local prefix="$1" index=0 subject
          shift
          for subject in "$@"; do
            index=$((index + 1))
            expect_accept "$prefix-$index" "$subject"
          done
        }

        reject_each() {
          local prefix="$1" index=0 subject
          shift
          for subject in "$@"; do
            index=$((index + 1))
            expect_reject "$prefix-$index" "$subject"
          done
        }

        for type in feat fix refactor docs test build ci chore style perf revert; do
          expect_accept "valid-$type" "$type: 日本語の要約"
        done
        expect_accept comments "fix: 日本語の要約" "# Git が追加するコメント"
        expect_accept tailwind "docs: Created with Tailwind の例の修正"
        expect_accept non-attribution "fix: Generated by maintainer の表記の修正"
        expect_accept samurai "fix: Samurai により生成する処理の修正"
        accept_each noun-ending \
          "fix: 設定の扱い" \
          "docs: 型の違い" \
          "docs: 手順のまとめ" \
          "refactor: 検査の見直し" \
          "feat: port の割り当て" \
          "fix: 起動順序の修正" \
          "feat: 一覧の絞り込み・件数の表示" \
          "feat: 検査の追加（段階1）" \
          "fix: 競合の防止 (#12)"

        japanese_limit="fix: "
        for _ in $(seq 1 45); do
          japanese_limit="''${japanese_limit}あ"
        done
        printf '%s\n' "$japanese_limit" > japanese-limit
        if ! LC_ALL=C bash "$hook" japanese-limit > japanese-limit.stdout 2> japanese-limit.stderr; then
          echo "commit-msg counted UTF-8 bytes instead of characters" >&2
          cat japanese-limit.stderr >&2
          exit 1
        fi

        expect_reject arbitrary "日本語の要約"
        expect_attribution attribution "fix: この commit は Codex により生成"
        expect_attribution attribution-period "fix: この commit は Codex により生成。"
        expect_attribution attribution-passive "fix: この commit は OpenAI により作成された。"
        expect_attribution attribution-exclamation "fix: この commit は AI によって執筆！"
        expect_attribution attribution-polite "fix: この commit は Codex により生成済みです"
        expect_attribution attribution-no-space "fix: この commit は Codexにより生成"
        expect_attribution attribution-generic-no-space "fix: この commit は AIにより生成"
        expect_attribution attribution-multiple-spaces "fix: Generated  by Codex の帰属"
        expect_attribution attribution-tab $'fix: Generated\tby Codex の帰属'
        expect_attribution openai-attribution "fix: この commit は OpenAI により生成"
        expect_reject scope "fix(agents): 日本語の要約"
        expect_reject tab $'fix:\t日本語の要約'
        expect_reject body "fix: 日本語の要約" "" "理由を本文に書く"
        expect_reject breaking "feat!: 日本語の要約"
        expect_reject english "fix: update README"
        expect_reject unknown-type "release: 日本語の要約"
        expect_reject over-limit "''${japanese_limit}あ"
        expect_reject touten "feat: 一覧の絞り込み、件数の表示"
        expect_reject kuten "fix: 起動順序の修正。"
        reject_each predicate-ending \
          "feat: 既定を無効にする" \
          "fix: 設定を直す" \
          "docs: 手順を書く" \
          "fix: 競合を防ぐ" \
          "feat: 型を組む" \
          "fix: 経路を選ぶ" \
          "fix: 検査が通らぬ" \
          "fix: 型を持つ" \
          "fix: 型を使う" \
          "fix: 設定を直した" \
          "fix: 経路を選んだ" \
          "fix: 起動を止めない" \
          "fix: 型の不一致は無い" \
          "fix: 既定値が正しい" \
          "feat: 型を揃えたい" \
          "feat: 検査を足す（段階1）" \
          "fix: 競合を防ぐ (#12)"
        reject_each particle-ending \
          "feat: 既定を無効に" \
          "docs: 記録を現在地へ" \
          "fix: 設定の既定を" \
          "fix: 起動の検査で" \
          "fix: 型の既定が" \
          "fix: 型の既定は"

        touch "$out"
      '';

}
